### ISSUE TITLE
Rename file paths of components imports 

### ISSUE THREAD

**Issue by d-a-ve** [GDGoC-University-of-Benin/the-intern-place#2]
Issue:
Rename the file paths of components and pages from the absolute path it is using now to use the import alias `@`.

Here are image screenshots for how they should look.

Before:
<img width="644" alt="Screenshot 2024-10-07 at 21 11 39" src="https://github.com/user-attachments/assets/02b5e243-9c29-49e9-ba2e-ed5da581a604">

After:
<img width="644" alt="Screenshot 2024-10-07 at 21 11 57" src="https://github.com/user-attachments/assets/6835ad13-9875-47d5-abf5-2f0fc14dccff">

**Comment by Sandee004** [comment]
I'll take it up

**Comment by d-a-ve** [comment]
Alright, it is yours.
